language: android
jdk: oraclejdk8
env:
 global:
    - ANDROID_API_LEVEL=26
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
sudo: false
android:
components:
- platform-tools
- tools
# The BuildTools version used by your project
- build-tools-$ANDROID_BUILD_TOOLS_VERSION
# The SDK version used to compile your project
- android-$ANDROID_API_LEVEL
- android-22
- sys-img-armeabi-v7a-android-22
- extra-android-m2repository

licenses:
- 'android-sdk-preview-license-.+'
- 'android-sdk-license-.+'
- 'google-gdk-license-.+'

before_script:
- mkdir -p "$ANDROID_HOME/licenses"
- cp ./google-licenses/* "$ANDROID_HOME/licenses/"

before_script:
# Create and start emulator
- echo no | android create avd --force -n test -b "system-images;android-22;google_apis;x86"
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
script: ./gradlew build connectedCheck